Repository jps27CSE/Gadgets-E-Commerce_React_Django, pull requests merged in 2023-10, with the labels that each got.

#17 setting up the banner section
  Frontend/src/Pages/Homepage.jsx
  Frontend/src/Pages/Products/Banner.jsx
  Frontend/src/image/30193.jpg
  Frontend/src/image/7995902.jpg
  Frontend/src/image/8642509.jpg
  Frontend/src/image/Gadget-Banner-Design-Template-scaled.jpg
  Frontend/src/image/black-friday-picwish.jpg
  Frontend/src/image/c72858992482c70d5ec3a585eec352ed.png
  package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#18 balance the height of the banner
  Frontend/src/Pages/Homepage.jsx
  Frontend/src/Pages/Products/Banner.jsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#20 HomeSlider API has been added.
  backend/db.sqlite3
  backend/sliders/flower.jpg
  backend/store/__pycache__/admin.cpython-311.pyc
  backend/store/__pycache__/models.cpython-311.pyc
  backend/store/admin.py
  backend/store/api/__pycache__/serializers.cpython-311.pyc
  backend/store/api/__pycache__/urls.cpython-311.pyc
  backend/store/api/__pycache__/views.cpython-311.pyc
  backend/store/api/serializers.py
  backend/store/api/urls.py
  backend/store/api/views.py
  backend/store/migrations/0002_homeslider_alter_brand_name_and_more.py
  backend/store/migrations/__pycache__/0002_homeslider_alter_brand_name_and_more.cpython-311.pyc
  backend/store/models.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#22 API Collection has been added
  backend/Store API Collection.postman_collection.json
  backend/store/api/__pycache__/urls.cpython-311.pyc
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023
